version: "3.7"
services:
  backend:
    container_name: msf-server
    restart: always
    image: msf-server:latest
    ports: 
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - express-mongo
  

  mongo:
    container_name: mongodb
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
networks:
  
  express-mongo: